### ISSUE TITLE
CSSModules with variables

### ISSUE THREAD

**Issue by misantronic** [fuse-box/fuse-box#1436]
The `CSSModulesPlugin` works well with FuseBox (https://fuse-box.org/docs/plugins/css-modules-plugin)
Now, I want to [export variables](https://github.com/css-modules/css-modules/blob/master/docs/values-variables.md). I think to make this work I have to install https://www.npmjs.com/package/postcss-modules-values.

```css
@value colors: "../vars/color.css";
@value palegrey from colors;

.container {
    border: 1px solid palegrey;
}
```

The first thing failing is the folder pointing to my css-file. It always does this:

```
{ Error: ENOENT: no such file or directory, open '/Users/ME/src/PROJECT/src/Users/ME/src/PROJECT/src/components/vars/color.css'
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/ME/src/PROJECT/src/Users/ME/src/PROJECT/src/components/vars/color.css' }
```

This is roughly fixed by adding an absolute path to the css-file (which is by far not a good solution).
Still, it's not working. 

The generated code looks like this:

```css
.container {
  border: 1px solid _palegrey___17fDG;
}
```

Is there more I have to consider when adding CSSModules to fuse-box? My plugin config:

```js
plugins: [
    ...
    [
        CSSModulesPlugin({
            root: path.resolve(__dirname, "src"),
        }),
        CSSPlugin()
    ],
    ...
]
```
