### ISSUE TITLE
injected css url not stringified in v4 productin build

### ISSUE THREAD

**Issue by jeremy-coleman** [fuse-box/fuse-box#1576]
maybe windows related, but from the v4 react demo , the css in the head gets injected as
 ```css
body{color:red;background-image:url(/resources/images/4a1ae6fe.png)}
```
instead of 
 ```css
body{color:red;background-image:url("/resources/images/4a1ae6fe.png")}
```
