### ISSUE TITLE
Scope scss import not working

### ISSUE THREAD

**Issue by fabien0102** [fuse-box/fuse-box#181]
Hello everybody!

I’m a beginner with fuse-box and just try (for instant) to connect it on a side project to test it.

This project is a little connect 4 game based on typescript, react, redux and jest. The main part is working out a the box (and incredibly fast!), but my sass import not following…

The problem:
```js
import * as styles from './Cells.scss';

// With webpack2
console.log(styles): // {"cell":"zwUPtEye2tlbA-q2Y2thD","empty":"_3cYPK1mkOVqkH7jBOYOpyG","redDisc":"lPujeNqdacgxwv4nAkzLl","projection":"_17A31djhrb9UDaEEvOVo6x","yellowDisc":"_1tJz8QL3Ozd-iNEi82Q8bI"}

// With fuse-box
console.log(styles); // {}
```

And same issue with generated css
```css
// With webpack 2
.zwUPtEye2tlbA-q2Y2thD {
  height: 60px;
  width: 60px;
  border-right: 10px solid blue;
  border-left: 10px solid blue; }

._3cYPK1mkOVqkH7jBOYOpyG {
  cursor: pointer;
  background: radial-gradient(ellipse at center, transparent 0%, transparent 59%, blue 60%, blue 100%); }

.lPujeNqdacgxwv4nAkzLl {
  background: radial-gradient(ellipse at center, #f00000 0, red 44%, #e60000 45%, #e60000, 59%, blue 60%, blue 100%); }
  .lPujeNqdacgxwv4nAkzLl._17A31djhrb9UDaEEvOVo6x {
    background: radial-gradient(ellipse at center, rgba(255, 0, 0, 0.5) 0%, rgba(255, 0, 0, 0.5) 59%, blue 60%, blue 100%); }

._1tJz8QL3Ozd-iNEi82Q8bI {
  background: radial-gradient(ellipse at center, #f0f000 0, yellow 44%, #e6e600 45%, #e6e600, 59%, blue 60%, blue 100%); }
  ._1tJz8QL3Ozd-iNEi82Q8bI._17A31djhrb9UDaEEvOVo6x {
    background: radial-gradient(ellipse at center, rgba(255, 255, 0, 0.5) 0%, rgba(255, 255, 0, 0.5) 59%, blue 60%, blue 100%); }

// With fuse-box
.cell{height:60px;width:60px;border-right:10px solid blue;border-left:10px solid blue}

.empty{cursor:pointer;background:radial-gradient(ellipse at center, transparent 0%, transparent 59%, blue 60%, blue 100%)}

.redDisc{background:radial-gradient(ellipse at center, #f00000 0, red 44%, #e60000 45%, #e60000, 59%, blue 60%, blue 100%)}

.redDisc.projection{background:radial-gradient(ellipse at center, rgba(255,0,0,0.5) 0%, rgba(255,0,0,0.5) 59%, blue 60%, blue 100%)}

.yellowDisc{background:radial-gradient(ellipse at center, #f0f000 0, #ff0 44%, #e6e600 45%, #e6e600, 59%, blue 60%, blue 100%)}

.yellowDisc.projection{background:radial-gradient(ellipse at center, rgba(255,255,0,0.5) 0%, rgba(255,255,0,0.5) 59%, blue 60%, blue 100%)}



```

All implementations details here -> https://github.com/fabien0102/connect4react/tree/fuse-box

I don’t know if it’s a real issue or just a personal fail, so if you someone have the solution, please tell me! :wink:
