### ISSUE TITLE
css background-image url with @ in path is not managed as resource

### ISSUE THREAD

**Issue by TiTi** [fuse-box/fuse-box#1995]
Hello,
One image referenced in the css doesn't have the appropriate path because of an "@" in the image filename 😢.

First i'm using this fusebox configuration (expecting production resources url to starts with /static/resources/):
```
    resources: {
      resourceFolder: './resources/',
      resourcePublicRoot: '/static/resources',
    }
```

But I got this unfortunately:
![image](https://user-images.githubusercontent.com/137691/117647808-c21b3480-b18d-11eb-80d8-78c1f01bbd41.png)
One is working, not the other!

The css is imported like so:
``` ts
import 'leaflet-fullscreen/dist/leaflet.fullscreen.css';
```

And here are the relevant parts of that file:
``` css
.leaflet-control-fullscreen a {
  background:#fff url(fullscreen.png) no-repeat 0 0;
  background-size:26px 52px;
  }

/* ...snip... */

@media
  (-webkit-min-device-pixel-ratio:2),
  (min-resolution:192dpi) {
    .leaflet-control-fullscreen a {
      background-image:url(fullscreen@2x.png);
    }
  }
```

We can see the filename "fullscreen@2x.png" is not even randomized compared to other resources fusebox manage.
I tried to remove the '@' (+ add the corresponding file) and everything's working as expected:
![image](https://user-images.githubusercontent.com/137691/117648729-de6ba100-b18e-11eb-86b8-dc7a6a382de4.png)

Unfortunately, this is not a .css i manage but one from a node package: `leaflet-fullscreen`
Thus a fix would be really helpful to avoid complex shenanigans.

[I'm also having the same issue with esri-leaflet-geocoder npm package and dist\img\search@2x.png]
