### ISSUE TITLE
How to handle assets in CSS/SCSS?

### ISSUE THREAD

**Issue by Martaver** [fuse-box/fuse-box#578]
Heya,

Does Fuse-box support assets/fonts etc in CSS/SCSS?

I have CSSModulesPlugin set up with SCSS, and I'm trying to use the following:

```css
.logo {
  height: 40px;
  background-image: url("./logo.svg");
  background-repeat: no-repeat;
}
```
`logo.svg` is in the same folder as the scss file.

I checked out the CSSResourcePlugin but it seems to be for an entirely different purpose. Can fuse-box handle this?
