### ISSUE TITLE
Travis CI cannot find module './plugins/images/ImageBase64Plugin'

### ISSUE THREAD

**Issue by TheGrimSilence** [fuse-box/fuse-box#899]
I've had my projects building on Travis CI for some time now, and my configurations hardly ever get changed between repositories. Recently, however, one of my projects has been persistently failing with the same error:

```
Error: Cannot find module './plugins/images/ImageBase64Plugin'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/TheGrimSilence/ebongarde.com/node_modules/fuse-box/src/index.ts:19:1)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
error Command failed with exit code 1.
```

The Travis CI repository page is: https://travis-ci.com/TheGrimSilence/ebongarde.com, but I'm unsure if you'll be able to see it. I've deleted every cache possible, I've run through the my source code, and there's no call from my code to this plugin, so I think it may come from Travis itself. 

For installations I use Yarn, and anything globally needed is added as such via a `before_script` config. It's a very recent error, and it ran fine for a week or so before it started.

**Comment by nchanged** [comment]
@TheGrimSilence 
```
We couldn't find the repository 
TheGrimSilence/ebongarde.com
```

We really need some here understanding the issue here

**Comment by TheGrimSilence** [comment]
Besides the raw log, The repository is private sadly.

**Comment by shripadk** [comment]
Faced same issue here. The folder `plugins/images` is missing from `node_modules/fuse-box/dist/commonjs/` when installing **fuse-box** with **yarn** but not with **npm**. 

Truncated some installation output for brevity:

```
$ yarn --version
1.2.1

$ yarn

$ ls node_modules/fuse-box/dist/commonjs/plugins/
BannerPlugin.js               HTMLplugin.js.map             RawPlugin.js                  UglifyJSPlugin.js.map
BannerPlugin.js.map           HotReloadPlugin.js            RawPlugin.js.map              VuePlugin.js
ConcatPlugin.js               HotReloadPlugin.js.map        ReplacePlugin.js              VuePlugin.js.map
ConcatPlugin.js.map           JSONplugin.js                 ReplacePlugin.js.map          WebIndexPlugin.js
ConsolidatePlugin.js          JSONplugin.js.map             SourceMapPlainJsPlugin.js     WebIndexPlugin.js.map
ConsolidatePlugin.js.map      Markdownplugin.js             SourceMapPlainJsPlugin.js.map js-transpilers
CopyPlugin.js                 Markdownplugin.js.map         TypeScriptHelpers.js          stylesheet
CopyPlugin.js.map             OptimizeJSPlugin.js           TypeScriptHelpers.js.map      vue
EnvPlugin.js                  OptimizeJSPlugin.js.map       UglifyESPlugin.js
EnvPlugin.js.map              PlainJSPlugin.js              UglifyESPlugin.js.map
HTMLplugin.js                 PlainJSPlugin.js.map          UglifyJSPlugin.js

$ rm -rf node_modules

$ npm --version
5.4.2

$ npm install

$ ls node_modules/fuse-box/dist/commonjs/plugins/
BannerPlugin.js               HTMLplugin.js.map             RawPlugin.js                  UglifyJSPlugin.js.map
BannerPlugin.js.map           HotReloadPlugin.js            RawPlugin.js.map              VuePlugin.js
ConcatPlugin.js               HotReloadPlugin.js.map        ReplacePlugin.js              VuePlugin.js.map
ConcatPlugin.js.map           JSONplugin.js                 ReplacePlugin.js.map          WebIndexPlugin.js
ConsolidatePlugin.js          JSONplugin.js.map             SourceMapPlainJsPlugin.js     WebIndexPlugin.js.map
ConsolidatePlugin.js.map      Markdownplugin.js             SourceMapPlainJsPlugin.js.map images
CopyPlugin.js                 Markdownplugin.js.map         TypeScriptHelpers.js          js-transpilers
CopyPlugin.js.map             OptimizeJSPlugin.js           TypeScriptHelpers.js.map      stylesheet
EnvPlugin.js                  OptimizeJSPlugin.js.map       UglifyESPlugin.js             vue
EnvPlugin.js.map              PlainJSPlugin.js              UglifyESPlugin.js.map
HTMLplugin.js                 PlainJSPlugin.js.map          UglifyJSPlugin.js
```

**Comment by TheGrimSilence** [comment]
I seem to have gotten it to work finally even with yarn. The following `.travis.yml` configuration works.
```yaml
sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: CC=clang CXX=clang++ npm_config_clang=1
      compiler: clang

addons:
  apt:
    packages:
      # Gotta stay updated
      - git-all

branches:
  only:
    - master
    - /^[0-9].[0-9].[0-9].*/

language: node_js
node_js:
  - "8"

cache:
  timeout: 600
  directories:
    - node_modules

install:
  - npm install -g yarn@1.2.1
  - yarn install --force

before_script:
  - yarn global add cross-env typescript ts-node rimraf

script:
  - yarn build:prod
  - ls -a

after_failure:
  - echo No post-failure script exists
```
After a new build ran all tests passed with alteration to my Fuse configuration
